---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2020/10/26 9:45
---

local _M = {}
local cp = require("component")
local me = cp.me_controller
local recipes = require("recipes")

function _M.findAssemblyLineCraftables()
    local craftables = me.getCraftables()
    for k, v in pairs(craftables) do
        local stack = v.getItemStack()
        if stack then
            local is = recipes[stack.name]
        end
    end
end

return _M
